### ISSUE TITLE
Blink Retreat: problem with path of length 1

### ISSUE THREAD

**Issue by mtesija** [honteam/Heroes-of-Newerth-Bots#69]
The current implementation for paths of length 1 (#tPath == 1) has the bots use their ability/item at the position of the path node. However this causes problems when that node is farther away than the range of the blink. To fix this, the bot should use their ability/item in the direction of the path node.

In short, this:

https://github.com/honteam/Heroes-of-Newerth-Bots/blob/Community/bots/behaviorLib.lua#L729

Needs to be changed to match this:

https://github.com/honteam/Heroes-of-Newerth-Bots/blob/Community/bots/behaviorLib.lua#L755

**Comment by Anakonda** [comment]
Nice find. Fixed
