### ISSUE TITLE
Core.GteItem is bugged

### ISSUE THREAD

**Issue by Schnarchnase** [honteam/Heroes-of-Newerth-Bots#70]
If it is called for the first time, it will be linked to the item.

If you move this item to the stash, you will receive the item-reference, although it may not be smart to do so. Resulting in odd behavior.

example: Activate Blight-Stones behavior and move runes to stash, resulting in getting stucked, if the bot want to eat a tree.

http://www7.pic-upload.de/04.05.14/884wnys8rwcc.png

**Comment by Schnarchnase** [comment]
A possible fix to this is to check, if the unit can access the item:

local bAccess = unitSelected:CanAccess(itemEntry.object) 
if bAccess or bIncludeStash then
   --do something
end

**Comment by Kairus101** [comment]
Good find, put it through as a pull request and I'll merge it in :)
